Transform: AWS::Serverless-2016-10-31

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      InlineCode: |
        const { BUCKET } = process.env;
        module.exports.handler = (event, context, callback) => {
          console.log('BUCKET:', BUCKET);
          callback(null, 'I GOT THE BUCKET!!!');
        };
      Handler: index.handler
