KeyName=ghostblog
StackName=ghost-blog
DbPassword=CaGHrN4cUpCzsQyzNsJ
DbRootPassword=K3AdmphXzjFAaisDXth
DbUser=ghostuser
DomainName=ghost.klickstuff.com
FromAddress=dvanbrunt@klick.com
HostedZoneId=ZBFSBY8N4M62
SslEmail=dvanbrunt@klick.com
