KeyName=ghostblog
StackName=ghost-blog
DbPassword=Bp4qQkeTTKvtixtxWya
DbRootPassword=UyhGBptVmD4QHTEqGEi
DbUser=ghostuser
DomainName=ghost2.klickstuff.com
FromAddress=dvanbrunt@klick.com
HostedZoneId=ZBFSBY8N4M62
SslEmail=dvanbrunt@klick.com
