version: "1.0"
stages:
  - clone
  - test
  - package
  - deploy
steps:
  main_clone:
    stage: clone
    type: git-clone
    description: Cloning main repository...
    repo: ACloudGuru-Resources/course-mastering-aws-cloudformation
    revision: ${{CF_BRANCH}}
  test:
    stage: test
    title: Testing CloudFormation Template
    image: mesosphere/aws-cli
    working_directory: "${{main_clone}}/Ch04 - Best Practises/L04 - Template Storage and Revisions/"
    environment:
      - AWS_DEFAULT_REGION=${{CLOUDGURU_REGION}}
      - AWS_ACCESS_KEY_ID=${{CLOUDGURU_ACCESS_KEY_ID}}
      - AWS_SECRET_ACCESS_KEY=${{CLOUDGURU_SECRET_ACCESS_KEY_ID}}
    commands:
      - aws cloudformation validate-template \
        --template-body file://template.yaml
  package:
    stage: package
    title: Packaging CloudFormation Template
    image: mesosphere/aws-cli
    working_directory: "${{main_clone}}/Ch04 - Best Practises/L04 - Template Storage and Revisions/"
    environment:
      - AWS_DEFAULT_REGION=${{CLOUDGURU_REGION}}
      - AWS_ACCESS_KEY_ID=${{CLOUDGURU_ACCESS_KEY_ID}}
      - AWS_SECRET_ACCESS_KEY=${{CLOUDGURU_SECRET_ACCESS_KEY_ID}}
    commands:
      - aws cloudformation package \
        --template-file template.yaml \
        --s3-bucket ${{CLOUDGURU_DEPLOY_BUCKET}} \
        --output-template-file packaged.yaml
  deploy:
    stage: deploy
    title: Deploying Template to S3
    image: mesosphere/aws-cli
    working_directory: "${{main_clone}}/Ch04 - Best Practises/L04 - Template Storage and Revisions/"
    environment:
      - AWS_DEFAULT_REGION=${{CLOUDGURU_REGION}}
      - AWS_ACCESS_KEY_ID=${{CLOUDGURU_ACCESS_KEY_ID}}
      - AWS_SECRET_ACCESS_KEY=${{CLOUDGURU_SECRET_ACCESS_KEY_ID}}
    commands:
      - aws s3 sync \
        . s3://$DEPLOY_BUCKET/templates/projectx \
        --exclude "*" \
        --include "*.yaml"
