Parameters:
  StageParameter:
    Type: String
    Default: dev
    Description: Feature Branch Name
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
  ProxyEntry:
    Type: Custom::MarketingStackProxyEntry
    Version: 1.0
    Properties:
      ServiceToken: !ImportValue stack-proxy-proxyentry-lambda-arn
      Service: !Ref AWS::StackName
      Stage: !Ref StageParameter
      Origin: !GetAtt WebsiteBucket.DomainName

Outputs:
  SiteURL:
    Description: URL for this site
    Value: !Sub
      - https://${Domain}
      - { Domain: !GetAtt ProxyEntry.Host }
