Resources:
  Bucket:
    Type: AWS::S3::Bucket

  Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: BucketArn
          Value: !Ref Bucket

  WaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    DependsOn: Bucket
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT1M

Outputs:
  # Passing the Bucket reference back out
  Bucket:
    Description: Super Cool S3 Bucket
    Value: !Ref Bucket
