Parameters:
  CourseBucketParam:
    Type: String
    Description: Course bucket we setup in first chapter
  BucketPathParam:
    Type: String
    Default: /coursefiles/nestedstacks
    Description: Path to template files
Resources:
  StackBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CourseBucketParam}.s3.amazonaws.com${BucketPathParam}/child1.yaml

  StackLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketParam: !GetAtt StackBucket.Outputs.Bucket
      TemplateURL: !Sub https://${CourseBucketParam}.s3.amazonaws.com${BucketPathParam}/child2.yaml

Outputs:
  MasterBucket:
    Description: Bucket from Child Stack
    Value: !GetAtt StackBucket.Outputs.Bucket
  MasterLambdaARN:
    Description: Lambda from Child Stack
    Value: !GetAtt StackLambda.Outputs.LambdaARN
