Transform: AWS::Serverless-2016-10-31

Description: Macro CommonTags

Resources:
  MacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      CodeUri: src
      Handler: index.handler
