Transform: AWS::Serverless-2016-10-31

Resources:
  TransformFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: src
      Handler: index.handler

  TransformFunctionPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt TransformFunction.Arn
      Principal: cloudformation.amazonaws.com

  Transform:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: String
      Description: Provides various string processing functions
      FunctionName: !GetAtt TransformFunction.Arn
