Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    Handler: index.handler

Parameters:
  DomainParam:
    Type: String
    Description: Domain to be extended with subdomains Eg. domain.com or sub.domain.com
  GitHubWebhookSecretParam:
    Type: String
    Description: GitHub Webhook Secret
  SSLCertARN:
    Type: String
    Description: WildCard SSL Certificate ARN

Resources:
  DefaultBucket:
    Type: AWS::S3::Bucket
  DefaultBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: DefaultBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            AWS: !GetAtt OriginRequestRole.Arn
            CanonicalUser: !GetAtt CloudfrontOAI.S3CanonicalUserId
          Action:
            - s3:ListBucket
            - s3:GetObject
          Resource:
            - !Sub arn:aws:s3:::${DefaultBucket}
            - !Sub arn:aws:s3:::${DefaultBucket}/*
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
  ProxyEntryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      CodeUri: src/proxyentry
      Role: !GetAtt ProxyEntryRole.Arn
      Environment:
        Variables:
          ORIGINMAP_TABLE: !Ref OriginMapTBL
          DOMAIN: !Ref DomainParam
          ORIGINREQUEST_LAMBDA_ARN: !GetAtt OriginRequestFunction.Arn
          ORIGINREQUEST_ROLE_ARN: !GetAtt OriginRequestRole.Arn
          OriginRequestProxyRoleARN: !GetAtt OriginRequestProxyRole.Arn
          OriginResponseLambdaARN: !GetAtt OriginResponseFunction.Arn
          CloudfrontOAI: !GetAtt CloudfrontOAI.S3CanonicalUserId
  StackProxyMacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      CodeUri: src/macro-proxyentry
      Environment:
        Variables:
          PROXYENTRY_ARN: !GetAtt ProxyEntryFunction.Arn
  StackProxyMacroLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${StackProxyMacroFunction}
      RetentionInDays: 3
  StackProxyMacro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: ACG-StackProxy-2020-02-16
      FunctionName: !GetAtt StackProxyMacroFunction.Arn
  ProxyEntryRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${AWS::StackName}-proxyentry-rolespo
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-proxyentry-role
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/stack-proxy-*"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/stack-proxy-*/index/*"
  OriginRequestProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-originrequestproxy
      CodeUri: src/originrequestproxy
      Handler: index.handler
      MemorySize: 512
      AutoPublishAlias: live
      Role: !GetAtt OriginRequestProxyRole.Arn
  OriginRequestProxyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${OriginRequestProxyFunction}
      RetentionInDays: 3
  OriginRequestProxyRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${AWS::StackName}-originrequestproxy-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-originrequestproxy-role
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${DefaultBucket}
                  - !Sub arn:aws:s3:::${DefaultBucket}/*
                  - arn:aws:s3:::*
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AWS::StackName}-*
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AWS::StackName}-*/index/*
  OriginRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/originrequest
      MemorySize: 512
      AutoPublishAlias: live
      Role: !GetAtt OriginRequestRole.Arn
  OriginRequestLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${OriginRequestFunction}
      RetentionInDays: 3
  OriginRequestRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${AWS::StackName}-originrequest-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-originrequest-role
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: arn:aws:logs:*:*:*
  OriginResponseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/originresponse
      MemorySize: 128
      AutoPublishAlias: live
      Role: !GetAtt OriginResponseRole.Arn
  OriginResponseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${OriginResponseFunction}
      RetentionInDays: 3
  OriginResponseRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${AWS::StackName}-originresponse-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-originresponse-role
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: arn:aws:logs:*:*:*
  GithubWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      CodeUri: src/githubwebhook
      MemorySize: 256
      AutoPublishAlias: live
      Role: !GetAtt GithubWebhookRole.Arn
      Events:
        DeleteBranchHook:
          Type: Api
          Properties:
            Path: /deletebranch
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Environment:
        Variables:
          GITHUB_WEBHOOK_SECRET: !Ref GitHubWebhookSecretParam
          PROD_CI_ROLE_ARN: !GetAtt DeployerRole.Arn
          DEV_CI_ROLE_ARN: !GetAtt DeployerRole.Arn
  GithubWebhookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${GithubWebhookFunction}
      RetentionInDays: 3
  GithubWebhookRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${AWS::StackName}-githubwebhookrole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-githubwebhookrole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - cloudformation:DeleteStack
                Resource:
                  - arn:aws:cloudformation:*:*:stack/*-rc-*/*
                  - arn:aws:cloudformation:*:*:stack/*-feat-*/*
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeAccountLimits
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackInstance
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStackSet
                  - cloudformation:DescribeStackSetOperation
                  - cloudformation:EstimateTemplateCost
                  - cloudformation:GetStackPolicy
                  - cloudformation:GetTemplate
                  - cloudformation:GetTemplateSummary
                  - iam:PassRole
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - arn:aws:s3:::*-rc-*
                  - arn:aws:s3:::*-feat-*
  DeployerRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${AWS::StackName}-deployer-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-deployer-role
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "*"
                Resource: "*"
  OriginMapTBL:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-domainmap
      AttributeDefinitions:
        - AttributeName: Host
          AttributeType: S
      KeySchema:
        - AttributeName: Host
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 5
  CloudfrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub Created for ${AWS::StackName}
  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "*.${DomainParam}"
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        IPV6Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
            Headers:
              - Host
              - CloudFront-Viewer-Country
              - Accept-Language
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          TargetOriginId: WebsiteBucketOrigin
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref OriginRequestProxyFunction.Version
            - EventType: origin-response
              LambdaFunctionARN: !Ref OriginResponseFunction.Version
        Origins:
          - DomainName: !GetAtt DefaultBucket.DomainName
            Id: WebsiteBucketOrigin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudfrontOAI}
  DnsRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub ${DomainParam}.
      Comment: !Sub DNS records associated with ${AWS::StackName}
      RecordSets:
        - Name: !Sub "*.${DomainParam}."
          Type: A
          AliasTarget:
            DNSName: !GetAtt CDN.DomainName
            HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  ProxyEntryLambdaARN:
    Description: ProxyEntry Lambda ARN
    Value: !GetAtt ProxyEntryFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-proxyentry-lambda-arn
  OriginRequestLambdaARN:
    Description: OriginRequest Lambda ARN
    Value: !GetAtt OriginRequestFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-originrequest-lambda-arn
  OriginRequestRoleARN:
    Description: OriginRequest Role ARN
    Value: !GetAtt OriginRequestRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-originrequest-role-arn
  OriginRequestProxyRoleARN:
    Description: OriginRequestProxy Role ARN
    Value: !GetAtt OriginRequestProxyRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-originrequestproxy-role-arn
  OriginResponseLambdaARN:
    Description: OriginResponse Lambda ARN
    Value: !GetAtt OriginResponseFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-originresponse-lambda-arn
  CloudfrontOAI:
    Description: Proxy CloudFront Origin Access Identity S3CanonicalUserId
    Value: !GetAtt CloudfrontOAI.S3CanonicalUserId
    Export:
      Name: !Sub ${AWS::StackName}-cloudfrontoai
  GitHubWebhook:
    Description: Endpoint for the GitHub Webhook
    Value: !Sub https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/deletebranch
