Transform: AWS::Serverless-2016-10-31

Resources:
  ResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: src
      Handler: resource.handler
      Policies: AmazonS3FullAccess
      Environment:
        Variables:
          REGION: !Ref AWS::Region

  MacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: src
      Handler: index.handler
