name: JAMStack Deployment

on:
  push:
    branches:
      - feat-*

jobs:
  build-deploy:
    name: Backend and Frontend Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      DEPLOY_BUCKET: acg-deploy-bucket
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build & Deploy
        working-directory: "${{ github.workspace }}/Ch07 - Work with Serverless/JAMStack Deployment"
        run: |
          npm config set scripts-prepend-node-path auto # https://bit.ly/3cKK2Uf
          yarn install
          yarn build:backend
          yarn deploy:backend \
            STAGE=${GITHUB_REF##*/} \
            STAGE_FLAG=dev \
            REGION=$AWS_DEFAULT_REGION \
            DEPLOY_BUCKET=$DEPLOY_BUCKET
          yarn build:frontend
          yarn deploy:frontend \
            STAGE=${GITHUB_REF##*/} \
            STAGE_FLAG=dev \
            REGION=$AWS_DEFAULT_REGION
  # Other Ideas:
  # Lighthouse jakejarvis/lighthouse-action@master
  # Slack  https://github.com/marketplace/actions/slack-notify
