name: Lint CloudFormation Templates

on: [push]

jobs:
  cloudformation-linter:
    env:
      TEMPLATE_LOCATION: ./Ch04 - Best Practises/L04 - Template Storage and Revisions
      DEPLOY_BUCKET: acg-deploy-bucket 
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Lint Templates
      uses: ScottBrenner/cfn-lint-action@1.3.0
      with:
        args: "**/*.yaml"
         
    - name: Package to S3
      run: |
        aws cloudformation package \
          --template-file "$TEMPLATE_LOCATION/template.yaml" \
          --s3-bucket $DEPLOY_BUCKET \
          --output-template-file "$TEMPLATE_LOCATION/packaged.yaml" \
          --region $AWS_DEFAULT_REGION

    - name: Deploy Template to S3
      run: |
        cat "$TEMPLATE_LOCATION/packaged.yaml"
        aws s3 sync \
          "$TEMPLATE_LOCATION" s3://$DEPLOY_BUCKET/coursefiles/nestedstacks \
          --exclude "*" \
          --include "packaged.yaml" \
          --region $AWS_DEFAULT_REGION
