name: Lint CloudFormation Templates

on: [push]

jobs:
  cloudformation-linter:
    env:
      TEMPLATE_LOCATION: ./Ch04 - Best Practises/L04 - Template Storage and Revisions
      DEPLOY_BUCKET: acg-deploy-bucket 
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: cfn-lint-action
      uses: ScottBrenner/cfn-lint-action@1.3.0
      with:
        args: "**/*.yaml"
         
    - name: Package to S3
      run: |
        aws cloudformation package \
          --template-file $TEMPLATE_LOCATION/template.yaml \
          --s3-bucket $DEPLOY_BUCKET \
          --output-template-file $TEMPLATE_LOCATION/packaged.yaml \
          --region $AWS_DEFAULT_REGION
        cat $TEMPLATE_LOCATION/packaged.yaml

    - name: Deploy Template to S3
      run: |
        aws s3 sync \
          . s3://$DEPLOY_BUCKET/coursefiles/nestedstacks \
          --exclude "*" \
          --include $TEMPLATE_LOCATION/packaged.yaml \
          --region $AWS_DEFAULT_REGION
